# spring.application.name=shopping

server:
  port: 8082
  servlet:
    multipart:
      enabled : true
      maxFileSize: 10MB
      maxRequestSize: 100MB
spring:
  profiles:
    include: private
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=Asia/Seoul
    username: root
    password: zksxkxk$722
  http:
    multipart:
      enabled: true
      location: /upload[

  application:
    name: shopping

